site_name: Roni Analytics

# Themes related data--------------------------------------------------------------------------
theme:
  
  language: en # Language set to english

  
  font: # Font family selection
    text: Consolas # Text font
    code: monaco

  # Logo image
  logo: assets/transpwhitebig.png
  favicon: assets/transpwhitebig.png

  # Navigation bar
  features:
      - search.suggest
      - navigation.instant
      - navigation.sections
      - navigation.expand
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.tracking
      - navigation.prune
      - content.tabs.link
      - content.code.annotate

  # Settings for dark/light/automatic theme
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

#themeENDS-------------------------------------------------------------------------------------------
 

# Custom css file for custom styling
extra_css:
  - stylesheets/extra.css

# Footer section icons
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/RoniAnalytics
      name: Roni Analytics Twitter
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/roni-analytics-llp
      name: Roni Analytics Linkedin

copyright: MIT License Copyright (c) 2022 Roni Analytics


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences: 
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js


plugins:
  - glightbox
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  